apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops

resources:
- ../welcome-k8s/overlays/default/
- test-job.yaml
- test-sa-rbac.yaml
- test-sa.yaml
- test-cronjob.yaml
